//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProduccionAzucar.Models.Fincas
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro_sembrado
    {
        public int cod_sembrado { get; set; }
        public Nullable<decimal> cantidad_sembrado { get; set; }
        public string unidad_sembrado { get; set; }
        public Nullable<int> cod_brote { get; set; }
        public Nullable<decimal> cantidad_fertilizante { get; set; }
        public string unidad_fertilizante { get; set; }
        public Nullable<int> cod_fertilizante { get; set; }
        public Nullable<int> cod_finca { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string usuario_creacion { get; set; }
    
        public virtual fincas fincas { get; set; }
    }
}
