//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProduccionAzucar.Models.InventarioProduccion
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro_produccion
    {
        public int correlativo { get; set; }
        public string materia_prima { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string unidad_m { get; set; }
        public string estado { get; set; }
        public Nullable<int> cod_producto { get; set; }
        public string producto { get; set; }
        public Nullable<decimal> cantidad_producida { get; set; }
        public string unidad_p { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> cod_materia { get; set; }
    
        public virtual inventario_produccion inventario_produccion { get; set; }
    }
}
