//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProduccionAzucar.Models.Vehiculos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculos
    {
        public string placa { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public int capacidad { get; set; }
        public string motorista { get; set; }
        public string estado_ingreso { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string disponibilidad { get; set; }
        public int estado_registro { get; set; }
    }
}
