//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProduccionAzucar.Models.Pedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_inventario_central_p
    {
        public int correlativo { get; set; }
        public int cod_materia_prima { get; set; }
        public decimal cantidad { get; set; }
        public int cod_cat { get; set; }
        public string comentario { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string usuario_creacion { get; set; }
    
        public virtual inventario_central_p inventario_central { get; set; }
    }
}
