//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProduccionAzucar.Models.Pedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario_finca_produccion
    {
        public int cod_materia { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string unidad { get; set; }
        public string tipo_materia { get; set; }
    }
}
