//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProduccionAzucar.Models.Pedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class motoristas_p
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public motoristas_p()
        {
            this.vehiculos = new HashSet<vehiculos_p>();
        }
    
        public int idDUI { get; set; }
        public string motorista { get; set; }
        public int edadMot { get; set; }
        public string genMot { get; set; }
        public string tipoLicMot { get; set; }
        public string placa { get; set; }
        public int Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehiculos_p> vehiculos { get; set; }
    }
}
