//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProduccionAzucar.Models.Pedidos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PedidosEntities : DbContext
    {
        public PedidosEntities()
            : base("name=PedidosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<inventario_central_p> inventario_central_p { get; set; }
        public virtual DbSet<historial_inventario_central_p> historial_inventario_central_p { get; set; }
        public virtual DbSet<motoristas_p> motoristas_p { get; set; }
        public virtual DbSet<vehiculos_p> vehiculos_p { get; set; }
        public virtual DbSet<pedidos_canha> pedidos_canha { get; set; }
        public virtual DbSet<inventario_finca_produccion> inventario_finca_produccion { get; set; }
    }
}
