//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProduccionAzucar.Models.Pedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos_canha
    {
        public int correlativo { get; set; }
        public string descripcion { get; set; }
        public decimal cant_pedido { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_pedido { get; set; }
        public string usuario_pedido { get; set; }
        public string prioridad { get; set; }
        public Nullable<System.DateTime> fecha_deseada { get; set; }
        public Nullable<System.DateTime> fecha_recibida { get; set; }
        public string placa_vehiculo { get; set; }
    }
}
