//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProduccionAzucar.Models.Motoristas
{
    using System;
    using System.Collections.Generic;
    
    public partial class motoristas
    {
        public int idDUI { get; set; }
        public string motorista { get; set; }
        public int edadMot { get; set; }
        public string genMot { get; set; }
        public string tipoLicMot { get; set; }
        public string placa { get; set; }
        public int Estado { get; set; }
    }
}
