//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProduccionAzucar.Models.MateriaPrima
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_motivo_trans_inv_finca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_motivo_trans_inv_finca()
        {
            this.historial_inventario_finca = new HashSet<historial_inventario_finca>();
        }
    
        public int cod_cat { get; set; }
        public string motivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historial_inventario_finca> historial_inventario_finca { get; set; }
    }
}
