//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProduccionAzucar.Models.MateriaPrima
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario_finca
    {
        public int cod_materia_prima { get; set; }
        public Nullable<int> cod_finca { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string unidad { get; set; }
        public string tipo_materia { get; set; }
    
        public virtual fincas fincas { get; set; }
    }
}
