//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProduccionAzucar.Models.MateriaPrima
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario_finca
    {
        public int cod_materia_prima { get; set; }
        public Nullable<int> cod_finca { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string unidad { get; set; }
    
        public virtual fincas fincas { get; set; }
    }
}
