//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProduccionAzucar.Models.MateriaPrima
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MateriaPrimaEntities : DbContext
    {
        public MateriaPrimaEntities()
            : base("name=MateriaPrimaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_motivo_trans_inv_finca> cat_motivo_trans_inv_finca { get; set; }
        public virtual DbSet<fincas> fincas { get; set; }
        public virtual DbSet<historial_inventario_finca> historial_inventario_finca { get; set; }
        public virtual DbSet<inventario_finca> inventario_finca { get; set; }
    }
}
