//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProduccionAzucar.Models.MateriaPrimaCentral
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MateriaPrimaCentralEntities : DbContext
    {
        public MateriaPrimaCentralEntities()
            : base("name=MateriaPrimaCentralEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_motivo_trans_inv_central> cat_motivo_trans_inv_central { get; set; }
        public virtual DbSet<historial_inventario_central> historial_inventario_central { get; set; }
        public virtual DbSet<inventario_central> inventario_central { get; set; }
    }
}
